//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("mdbEdm", "FK_Manga_Publisher", "m_publisherInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(mraSharp.m_publisherInfo), "m_mangaInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mraSharp.m_mangaInfo), true)]
[assembly: EdmRelationshipAttribute("mdbEdm", "FK_Manga_ReadingList", "m_mangaInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(mraSharp.m_mangaInfo), "mr_readingList", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mraSharp.mr_readingList), true)]
[assembly: EdmRelationshipAttribute("mdbEdm", "mm_mangaAuthors", "m_authorInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mraSharp.m_authorInfo), "m_mangaInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mraSharp.m_mangaInfo))]
[assembly: EdmRelationshipAttribute("mdbEdm", "mm_mangaGenres", "m_genreInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mraSharp.m_genreInfo), "m_mangaInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(mraSharp.m_mangaInfo))]

#endregion

namespace mraSharp
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class mdbEdmContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new mdbEdmContainer object using the connection string found in the 'mdbEdmContainer' section of the application configuration file.
        /// </summary>
        public mdbEdmContainer() : base("name=mdbEdmContainer", "mdbEdmContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mdbEdmContainer object.
        /// </summary>
        public mdbEdmContainer(string connectionString) : base(connectionString, "mdbEdmContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new mdbEdmContainer object.
        /// </summary>
        public mdbEdmContainer(EntityConnection connection) : base(connection, "mdbEdmContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<m_authorInfo> m_authorInfo
        {
            get
            {
                if ((_m_authorInfo == null))
                {
                    _m_authorInfo = base.CreateObjectSet<m_authorInfo>("m_authorInfo");
                }
                return _m_authorInfo;
            }
        }
        private ObjectSet<m_authorInfo> _m_authorInfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<m_genreInfo> m_genreInfo
        {
            get
            {
                if ((_m_genreInfo == null))
                {
                    _m_genreInfo = base.CreateObjectSet<m_genreInfo>("m_genreInfo");
                }
                return _m_genreInfo;
            }
        }
        private ObjectSet<m_genreInfo> _m_genreInfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<m_mangaInfo> m_mangaInfo
        {
            get
            {
                if ((_m_mangaInfo == null))
                {
                    _m_mangaInfo = base.CreateObjectSet<m_mangaInfo>("m_mangaInfo");
                }
                return _m_mangaInfo;
            }
        }
        private ObjectSet<m_mangaInfo> _m_mangaInfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<m_publisherInfo> m_publisherInfo
        {
            get
            {
                if ((_m_publisherInfo == null))
                {
                    _m_publisherInfo = base.CreateObjectSet<m_publisherInfo>("m_publisherInfo");
                }
                return _m_publisherInfo;
            }
        }
        private ObjectSet<m_publisherInfo> _m_publisherInfo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<mr_readingList> mr_readingList
        {
            get
            {
                if ((_mr_readingList == null))
                {
                    _mr_readingList = base.CreateObjectSet<mr_readingList>("mr_readingList");
                }
                return _mr_readingList;
            }
        }
        private ObjectSet<mr_readingList> _mr_readingList;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rss_NewsStorage> rss_NewsStorage
        {
            get
            {
                if ((_rss_NewsStorage == null))
                {
                    _rss_NewsStorage = base.CreateObjectSet<rss_NewsStorage>("rss_NewsStorage");
                }
                return _rss_NewsStorage;
            }
        }
        private ObjectSet<rss_NewsStorage> _rss_NewsStorage;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rss_Subscriptions> rss_Subscriptions
        {
            get
            {
                if ((_rss_Subscriptions == null))
                {
                    _rss_Subscriptions = base.CreateObjectSet<rss_Subscriptions>("rss_Subscriptions");
                }
                return _rss_Subscriptions;
            }
        }
        private ObjectSet<rss_Subscriptions> _rss_Subscriptions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the m_authorInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTom_authorInfo(m_authorInfo m_authorInfo)
        {
            base.AddObject("m_authorInfo", m_authorInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the m_genreInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTom_genreInfo(m_genreInfo m_genreInfo)
        {
            base.AddObject("m_genreInfo", m_genreInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the m_mangaInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTom_mangaInfo(m_mangaInfo m_mangaInfo)
        {
            base.AddObject("m_mangaInfo", m_mangaInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the m_publisherInfo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTom_publisherInfo(m_publisherInfo m_publisherInfo)
        {
            base.AddObject("m_publisherInfo", m_publisherInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the mr_readingList EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomr_readingList(mr_readingList mr_readingList)
        {
            base.AddObject("mr_readingList", mr_readingList);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rss_NewsStorage EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorss_NewsStorage(rss_NewsStorage rss_NewsStorage)
        {
            base.AddObject("rss_NewsStorage", rss_NewsStorage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rss_Subscriptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorss_Subscriptions(rss_Subscriptions rss_Subscriptions)
        {
            base.AddObject("rss_Subscriptions", rss_Subscriptions);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdbEdm", Name="m_authorInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class m_authorInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new m_authorInfo object.
        /// </summary>
        /// <param name="authorID">Initial value of the authorID property.</param>
        /// <param name="authorFullName">Initial value of the authorFullName property.</param>
        public static m_authorInfo Createm_authorInfo(global::System.Int32 authorID, global::System.String authorFullName)
        {
            m_authorInfo m_authorInfo = new m_authorInfo();
            m_authorInfo.authorID = authorID;
            m_authorInfo.authorFullName = authorFullName;
            return m_authorInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 authorID
        {
            get
            {
                return _authorID;
            }
            set
            {
                if (_authorID != value)
                {
                    OnauthorIDChanging(value);
                    ReportPropertyChanging("authorID");
                    _authorID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("authorID");
                    OnauthorIDChanged();
                }
            }
        }
        private global::System.Int32 _authorID;
        partial void OnauthorIDChanging(global::System.Int32 value);
        partial void OnauthorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String authorFullName
        {
            get
            {
                return _authorFullName;
            }
            set
            {
                OnauthorFullNameChanging(value);
                ReportPropertyChanging("authorFullName");
                _authorFullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("authorFullName");
                OnauthorFullNameChanged();
            }
        }
        private global::System.String _authorFullName;
        partial void OnauthorFullNameChanging(global::System.String value);
        partial void OnauthorFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String authorCountryOfOrigin
        {
            get
            {
                return _authorCountryOfOrigin;
            }
            set
            {
                OnauthorCountryOfOriginChanging(value);
                ReportPropertyChanging("authorCountryOfOrigin");
                _authorCountryOfOrigin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("authorCountryOfOrigin");
                OnauthorCountryOfOriginChanged();
            }
        }
        private global::System.String _authorCountryOfOrigin;
        partial void OnauthorCountryOfOriginChanging(global::System.String value);
        partial void OnauthorCountryOfOriginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> authorDateOfBirth
        {
            get
            {
                return _authorDateOfBirth;
            }
            set
            {
                OnauthorDateOfBirthChanging(value);
                ReportPropertyChanging("authorDateOfBirth");
                _authorDateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("authorDateOfBirth");
                OnauthorDateOfBirthChanged();
            }
        }
        private Nullable<global::System.DateTime> _authorDateOfBirth;
        partial void OnauthorDateOfBirthChanging(Nullable<global::System.DateTime> value);
        partial void OnauthorDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String authorWebsite
        {
            get
            {
                return _authorWebsite;
            }
            set
            {
                OnauthorWebsiteChanging(value);
                ReportPropertyChanging("authorWebsite");
                _authorWebsite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("authorWebsite");
                OnauthorWebsiteChanged();
            }
        }
        private global::System.String _authorWebsite;
        partial void OnauthorWebsiteChanging(global::System.String value);
        partial void OnauthorWebsiteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdbEdm", "mm_mangaAuthors", "m_mangaInfo")]
        public EntityCollection<m_mangaInfo> m_mangaInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<m_mangaInfo>("mdbEdm.mm_mangaAuthors", "m_mangaInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<m_mangaInfo>("mdbEdm.mm_mangaAuthors", "m_mangaInfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdbEdm", Name="m_genreInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class m_genreInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new m_genreInfo object.
        /// </summary>
        /// <param name="genreID">Initial value of the genreID property.</param>
        /// <param name="genreName">Initial value of the genreName property.</param>
        public static m_genreInfo Createm_genreInfo(global::System.Int32 genreID, global::System.String genreName)
        {
            m_genreInfo m_genreInfo = new m_genreInfo();
            m_genreInfo.genreID = genreID;
            m_genreInfo.genreName = genreName;
            return m_genreInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 genreID
        {
            get
            {
                return _genreID;
            }
            set
            {
                if (_genreID != value)
                {
                    OngenreIDChanging(value);
                    ReportPropertyChanging("genreID");
                    _genreID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("genreID");
                    OngenreIDChanged();
                }
            }
        }
        private global::System.Int32 _genreID;
        partial void OngenreIDChanging(global::System.Int32 value);
        partial void OngenreIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String genreName
        {
            get
            {
                return _genreName;
            }
            set
            {
                OngenreNameChanging(value);
                ReportPropertyChanging("genreName");
                _genreName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("genreName");
                OngenreNameChanged();
            }
        }
        private global::System.String _genreName;
        partial void OngenreNameChanging(global::System.String value);
        partial void OngenreNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdbEdm", "mm_mangaGenres", "m_mangaInfo")]
        public EntityCollection<m_mangaInfo> m_mangaInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<m_mangaInfo>("mdbEdm.mm_mangaGenres", "m_mangaInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<m_mangaInfo>("mdbEdm.mm_mangaGenres", "m_mangaInfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdbEdm", Name="m_mangaInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class m_mangaInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new m_mangaInfo object.
        /// </summary>
        /// <param name="mangaID">Initial value of the mangaID property.</param>
        /// <param name="mangaTitle">Initial value of the mangaTitle property.</param>
        /// <param name="mangaStatus">Initial value of the mangaStatus property.</param>
        public static m_mangaInfo Createm_mangaInfo(global::System.Int32 mangaID, global::System.String mangaTitle, global::System.String mangaStatus)
        {
            m_mangaInfo m_mangaInfo = new m_mangaInfo();
            m_mangaInfo.mangaID = mangaID;
            m_mangaInfo.mangaTitle = mangaTitle;
            m_mangaInfo.mangaStatus = mangaStatus;
            return m_mangaInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mangaID
        {
            get
            {
                return _mangaID;
            }
            set
            {
                if (_mangaID != value)
                {
                    OnmangaIDChanging(value);
                    ReportPropertyChanging("mangaID");
                    _mangaID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mangaID");
                    OnmangaIDChanged();
                }
            }
        }
        private global::System.Int32 _mangaID;
        partial void OnmangaIDChanging(global::System.Int32 value);
        partial void OnmangaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mangaTitle
        {
            get
            {
                return _mangaTitle;
            }
            set
            {
                OnmangaTitleChanging(value);
                ReportPropertyChanging("mangaTitle");
                _mangaTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mangaTitle");
                OnmangaTitleChanged();
            }
        }
        private global::System.String _mangaTitle;
        partial void OnmangaTitleChanging(global::System.String value);
        partial void OnmangaTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mangaDescription
        {
            get
            {
                return _mangaDescription;
            }
            set
            {
                OnmangaDescriptionChanging(value);
                ReportPropertyChanging("mangaDescription");
                _mangaDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mangaDescription");
                OnmangaDescriptionChanged();
            }
        }
        private global::System.String _mangaDescription;
        partial void OnmangaDescriptionChanging(global::System.String value);
        partial void OnmangaDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> mangaYearOfPublisher
        {
            get
            {
                return _mangaYearOfPublisher;
            }
            set
            {
                OnmangaYearOfPublisherChanging(value);
                ReportPropertyChanging("mangaYearOfPublisher");
                _mangaYearOfPublisher = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mangaYearOfPublisher");
                OnmangaYearOfPublisherChanged();
            }
        }
        private Nullable<global::System.DateTime> _mangaYearOfPublisher;
        partial void OnmangaYearOfPublisherChanging(Nullable<global::System.DateTime> value);
        partial void OnmangaYearOfPublisherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mangaStatus
        {
            get
            {
                return _mangaStatus;
            }
            set
            {
                OnmangaStatusChanging(value);
                ReportPropertyChanging("mangaStatus");
                _mangaStatus = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mangaStatus");
                OnmangaStatusChanged();
            }
        }
        private global::System.String _mangaStatus;
        partial void OnmangaStatusChanging(global::System.String value);
        partial void OnmangaStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mangaPublisherID
        {
            get
            {
                return _mangaPublisherID;
            }
            set
            {
                OnmangaPublisherIDChanging(value);
                ReportPropertyChanging("mangaPublisherID");
                _mangaPublisherID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mangaPublisherID");
                OnmangaPublisherIDChanged();
            }
        }
        private Nullable<global::System.Int32> _mangaPublisherID;
        partial void OnmangaPublisherIDChanging(Nullable<global::System.Int32> value);
        partial void OnmangaPublisherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] mangaCover
        {
            get
            {
                return StructuralObject.GetValidValue(_mangaCover);
            }
            set
            {
                OnmangaCoverChanging(value);
                ReportPropertyChanging("mangaCover");
                _mangaCover = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mangaCover");
                OnmangaCoverChanged();
            }
        }
        private global::System.Byte[] _mangaCover;
        partial void OnmangaCoverChanging(global::System.Byte[] value);
        partial void OnmangaCoverChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdbEdm", "FK_Manga_Publisher", "m_publisherInfo")]
        public m_publisherInfo m_publisherInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<m_publisherInfo>("mdbEdm.FK_Manga_Publisher", "m_publisherInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<m_publisherInfo>("mdbEdm.FK_Manga_Publisher", "m_publisherInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<m_publisherInfo> m_publisherInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<m_publisherInfo>("mdbEdm.FK_Manga_Publisher", "m_publisherInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<m_publisherInfo>("mdbEdm.FK_Manga_Publisher", "m_publisherInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdbEdm", "FK_Manga_ReadingList", "mr_readingList")]
        public EntityCollection<mr_readingList> mr_readingList
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<mr_readingList>("mdbEdm.FK_Manga_ReadingList", "mr_readingList");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<mr_readingList>("mdbEdm.FK_Manga_ReadingList", "mr_readingList", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdbEdm", "mm_mangaAuthors", "m_authorInfo")]
        public EntityCollection<m_authorInfo> m_authorInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<m_authorInfo>("mdbEdm.mm_mangaAuthors", "m_authorInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<m_authorInfo>("mdbEdm.mm_mangaAuthors", "m_authorInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdbEdm", "mm_mangaGenres", "m_genreInfo")]
        public EntityCollection<m_genreInfo> m_genreInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<m_genreInfo>("mdbEdm.mm_mangaGenres", "m_genreInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<m_genreInfo>("mdbEdm.mm_mangaGenres", "m_genreInfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdbEdm", Name="m_publisherInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class m_publisherInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new m_publisherInfo object.
        /// </summary>
        /// <param name="publisherID">Initial value of the publisherID property.</param>
        /// <param name="publisherName">Initial value of the publisherName property.</param>
        public static m_publisherInfo Createm_publisherInfo(global::System.Int32 publisherID, global::System.String publisherName)
        {
            m_publisherInfo m_publisherInfo = new m_publisherInfo();
            m_publisherInfo.publisherID = publisherID;
            m_publisherInfo.publisherName = publisherName;
            return m_publisherInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 publisherID
        {
            get
            {
                return _publisherID;
            }
            set
            {
                if (_publisherID != value)
                {
                    OnpublisherIDChanging(value);
                    ReportPropertyChanging("publisherID");
                    _publisherID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("publisherID");
                    OnpublisherIDChanged();
                }
            }
        }
        private global::System.Int32 _publisherID;
        partial void OnpublisherIDChanging(global::System.Int32 value);
        partial void OnpublisherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String publisherName
        {
            get
            {
                return _publisherName;
            }
            set
            {
                OnpublisherNameChanging(value);
                ReportPropertyChanging("publisherName");
                _publisherName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("publisherName");
                OnpublisherNameChanged();
            }
        }
        private global::System.String _publisherName;
        partial void OnpublisherNameChanging(global::System.String value);
        partial void OnpublisherNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String publisherCountry
        {
            get
            {
                return _publisherCountry;
            }
            set
            {
                OnpublisherCountryChanging(value);
                ReportPropertyChanging("publisherCountry");
                _publisherCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("publisherCountry");
                OnpublisherCountryChanged();
            }
        }
        private global::System.String _publisherCountry;
        partial void OnpublisherCountryChanging(global::System.String value);
        partial void OnpublisherCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String publisherWebsite
        {
            get
            {
                return _publisherWebsite;
            }
            set
            {
                OnpublisherWebsiteChanging(value);
                ReportPropertyChanging("publisherWebsite");
                _publisherWebsite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("publisherWebsite");
                OnpublisherWebsiteChanged();
            }
        }
        private global::System.String _publisherWebsite;
        partial void OnpublisherWebsiteChanging(global::System.String value);
        partial void OnpublisherWebsiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String publisherNote
        {
            get
            {
                return _publisherNote;
            }
            set
            {
                OnpublisherNoteChanging(value);
                ReportPropertyChanging("publisherNote");
                _publisherNote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("publisherNote");
                OnpublisherNoteChanged();
            }
        }
        private global::System.String _publisherNote;
        partial void OnpublisherNoteChanging(global::System.String value);
        partial void OnpublisherNoteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdbEdm", "FK_Manga_Publisher", "m_mangaInfo")]
        public EntityCollection<m_mangaInfo> m_mangaInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<m_mangaInfo>("mdbEdm.FK_Manga_Publisher", "m_mangaInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<m_mangaInfo>("mdbEdm.FK_Manga_Publisher", "m_mangaInfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdbEdm", Name="mr_readingList")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class mr_readingList : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new mr_readingList object.
        /// </summary>
        /// <param name="entryID">Initial value of the entryID property.</param>
        /// <param name="mangaID">Initial value of the mangaID property.</param>
        /// <param name="mr_StartingChapter">Initial value of the mr_StartingChapter property.</param>
        /// <param name="mr_CurrentChapter">Initial value of the mr_CurrentChapter property.</param>
        /// <param name="mr_IsReadingFinished">Initial value of the mr_IsReadingFinished property.</param>
        public static mr_readingList Createmr_readingList(global::System.Int32 entryID, global::System.Int32 mangaID, global::System.Double mr_StartingChapter, global::System.Double mr_CurrentChapter, global::System.Boolean mr_IsReadingFinished)
        {
            mr_readingList mr_readingList = new mr_readingList();
            mr_readingList.entryID = entryID;
            mr_readingList.mangaID = mangaID;
            mr_readingList.mr_StartingChapter = mr_StartingChapter;
            mr_readingList.mr_CurrentChapter = mr_CurrentChapter;
            mr_readingList.mr_IsReadingFinished = mr_IsReadingFinished;
            return mr_readingList;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 entryID
        {
            get
            {
                return _entryID;
            }
            set
            {
                if (_entryID != value)
                {
                    OnentryIDChanging(value);
                    ReportPropertyChanging("entryID");
                    _entryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("entryID");
                    OnentryIDChanged();
                }
            }
        }
        private global::System.Int32 _entryID;
        partial void OnentryIDChanging(global::System.Int32 value);
        partial void OnentryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mangaID
        {
            get
            {
                return _mangaID;
            }
            set
            {
                OnmangaIDChanging(value);
                ReportPropertyChanging("mangaID");
                _mangaID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mangaID");
                OnmangaIDChanged();
            }
        }
        private global::System.Int32 _mangaID;
        partial void OnmangaIDChanging(global::System.Int32 value);
        partial void OnmangaIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double mr_StartingChapter
        {
            get
            {
                return _mr_StartingChapter;
            }
            set
            {
                Onmr_StartingChapterChanging(value);
                ReportPropertyChanging("mr_StartingChapter");
                _mr_StartingChapter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mr_StartingChapter");
                Onmr_StartingChapterChanged();
            }
        }
        private global::System.Double _mr_StartingChapter;
        partial void Onmr_StartingChapterChanging(global::System.Double value);
        partial void Onmr_StartingChapterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double mr_CurrentChapter
        {
            get
            {
                return _mr_CurrentChapter;
            }
            set
            {
                Onmr_CurrentChapterChanging(value);
                ReportPropertyChanging("mr_CurrentChapter");
                _mr_CurrentChapter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mr_CurrentChapter");
                Onmr_CurrentChapterChanged();
            }
        }
        private global::System.Double _mr_CurrentChapter;
        partial void Onmr_CurrentChapterChanging(global::System.Double value);
        partial void Onmr_CurrentChapterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mr_OnlineURL
        {
            get
            {
                return _mr_OnlineURL;
            }
            set
            {
                Onmr_OnlineURLChanging(value);
                ReportPropertyChanging("mr_OnlineURL");
                _mr_OnlineURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mr_OnlineURL");
                Onmr_OnlineURLChanged();
            }
        }
        private global::System.String _mr_OnlineURL;
        partial void Onmr_OnlineURLChanging(global::System.String value);
        partial void Onmr_OnlineURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean mr_IsReadingFinished
        {
            get
            {
                return _mr_IsReadingFinished;
            }
            set
            {
                Onmr_IsReadingFinishedChanging(value);
                ReportPropertyChanging("mr_IsReadingFinished");
                _mr_IsReadingFinished = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mr_IsReadingFinished");
                Onmr_IsReadingFinishedChanged();
            }
        }
        private global::System.Boolean _mr_IsReadingFinished;
        partial void Onmr_IsReadingFinishedChanging(global::System.Boolean value);
        partial void Onmr_IsReadingFinishedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> mr_LastRead
        {
            get
            {
                return _mr_LastRead;
            }
            set
            {
                Onmr_LastReadChanging(value);
                ReportPropertyChanging("mr_LastRead");
                _mr_LastRead = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mr_LastRead");
                Onmr_LastReadChanged();
            }
        }
        private Nullable<global::System.DateTime> _mr_LastRead;
        partial void Onmr_LastReadChanging(Nullable<global::System.DateTime> value);
        partial void Onmr_LastReadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mr_Note
        {
            get
            {
                return _mr_Note;
            }
            set
            {
                Onmr_NoteChanging(value);
                ReportPropertyChanging("mr_Note");
                _mr_Note = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mr_Note");
                Onmr_NoteChanged();
            }
        }
        private global::System.String _mr_Note;
        partial void Onmr_NoteChanging(global::System.String value);
        partial void Onmr_NoteChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("mdbEdm", "FK_Manga_ReadingList", "m_mangaInfo")]
        public m_mangaInfo m_mangaInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<m_mangaInfo>("mdbEdm.FK_Manga_ReadingList", "m_mangaInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<m_mangaInfo>("mdbEdm.FK_Manga_ReadingList", "m_mangaInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<m_mangaInfo> m_mangaInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<m_mangaInfo>("mdbEdm.FK_Manga_ReadingList", "m_mangaInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<m_mangaInfo>("mdbEdm.FK_Manga_ReadingList", "m_mangaInfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdbEdm", Name="rss_NewsStorage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rss_NewsStorage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rss_NewsStorage object.
        /// </summary>
        /// <param name="newsID">Initial value of the newsID property.</param>
        public static rss_NewsStorage Createrss_NewsStorage(global::System.Int32 newsID)
        {
            rss_NewsStorage rss_NewsStorage = new rss_NewsStorage();
            rss_NewsStorage.newsID = newsID;
            return rss_NewsStorage;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 newsID
        {
            get
            {
                return _newsID;
            }
            set
            {
                if (_newsID != value)
                {
                    OnnewsIDChanging(value);
                    ReportPropertyChanging("newsID");
                    _newsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("newsID");
                    OnnewsIDChanged();
                }
            }
        }
        private global::System.Int32 _newsID;
        partial void OnnewsIDChanging(global::System.Int32 value);
        partial void OnnewsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String newsTitle
        {
            get
            {
                return _newsTitle;
            }
            set
            {
                OnnewsTitleChanging(value);
                ReportPropertyChanging("newsTitle");
                _newsTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("newsTitle");
                OnnewsTitleChanged();
            }
        }
        private global::System.String _newsTitle;
        partial void OnnewsTitleChanging(global::System.String value);
        partial void OnnewsTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String newsLink
        {
            get
            {
                return _newsLink;
            }
            set
            {
                OnnewsLinkChanging(value);
                ReportPropertyChanging("newsLink");
                _newsLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("newsLink");
                OnnewsLinkChanged();
            }
        }
        private global::System.String _newsLink;
        partial void OnnewsLinkChanging(global::System.String value);
        partial void OnnewsLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String newsDescription
        {
            get
            {
                return _newsDescription;
            }
            set
            {
                OnnewsDescriptionChanging(value);
                ReportPropertyChanging("newsDescription");
                _newsDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("newsDescription");
                OnnewsDescriptionChanged();
            }
        }
        private global::System.String _newsDescription;
        partial void OnnewsDescriptionChanging(global::System.String value);
        partial void OnnewsDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> newsDatePublisher
        {
            get
            {
                return _newsDatePublisher;
            }
            set
            {
                OnnewsDatePublisherChanging(value);
                ReportPropertyChanging("newsDatePublisher");
                _newsDatePublisher = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("newsDatePublisher");
                OnnewsDatePublisherChanged();
            }
        }
        private Nullable<global::System.DateTime> _newsDatePublisher;
        partial void OnnewsDatePublisherChanging(Nullable<global::System.DateTime> value);
        partial void OnnewsDatePublisherChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> newsDateAquired
        {
            get
            {
                return _newsDateAquired;
            }
            set
            {
                OnnewsDateAquiredChanging(value);
                ReportPropertyChanging("newsDateAquired");
                _newsDateAquired = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("newsDateAquired");
                OnnewsDateAquiredChanged();
            }
        }
        private Nullable<global::System.DateTime> _newsDateAquired;
        partial void OnnewsDateAquiredChanging(Nullable<global::System.DateTime> value);
        partial void OnnewsDateAquiredChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="mdbEdm", Name="rss_Subscriptions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rss_Subscriptions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rss_Subscriptions object.
        /// </summary>
        /// <param name="rssID">Initial value of the rssID property.</param>
        /// <param name="rssURL">Initial value of the rssURL property.</param>
        public static rss_Subscriptions Createrss_Subscriptions(global::System.Int32 rssID, global::System.String rssURL)
        {
            rss_Subscriptions rss_Subscriptions = new rss_Subscriptions();
            rss_Subscriptions.rssID = rssID;
            rss_Subscriptions.rssURL = rssURL;
            return rss_Subscriptions;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rssID
        {
            get
            {
                return _rssID;
            }
            set
            {
                if (_rssID != value)
                {
                    OnrssIDChanging(value);
                    ReportPropertyChanging("rssID");
                    _rssID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rssID");
                    OnrssIDChanged();
                }
            }
        }
        private global::System.Int32 _rssID;
        partial void OnrssIDChanging(global::System.Int32 value);
        partial void OnrssIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rssURL
        {
            get
            {
                return _rssURL;
            }
            set
            {
                OnrssURLChanging(value);
                ReportPropertyChanging("rssURL");
                _rssURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rssURL");
                OnrssURLChanged();
            }
        }
        private global::System.String _rssURL;
        partial void OnrssURLChanging(global::System.String value);
        partial void OnrssURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rssChannelName
        {
            get
            {
                return _rssChannelName;
            }
            set
            {
                OnrssChannelNameChanging(value);
                ReportPropertyChanging("rssChannelName");
                _rssChannelName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rssChannelName");
                OnrssChannelNameChanged();
            }
        }
        private global::System.String _rssChannelName;
        partial void OnrssChannelNameChanging(global::System.String value);
        partial void OnrssChannelNameChanged();

        #endregion
    
    }

    #endregion
    
}
