//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mraNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mraNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [N/A].
        /// </summary>
        internal static string AddMangaForm_GetPublisherName__N_A_ {
            get {
                return ResourceManager.GetString("AddMangaForm_GetPublisherName__N_A_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap arrow_circle_double {
            get {
                object obj = ResourceManager.GetObject("arrow_circle_double", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar_48 {
            get {
                object obj = ResourceManager.GetObject("calendar_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calendar_day {
            get {
                object obj = ResourceManager.GetObject("calendar_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap exclamation_red {
            get {
                object obj = ResourceManager.GetObject("exclamation_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap globe_48 {
            get {
                object obj = ResourceManager.GetObject("globe_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to clear the database?.
        /// </summary>
        internal static string MainForm_ClearToolStripMenuItemClick_Are_you_sure_to_clear_the_database_ {
            get {
                return ResourceManager.GetString("MainForm_ClearToolStripMenuItemClick_Are_you_sure_to_clear_the_database_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string MainForm_ClearToolStripMenuItemClick_Question {
            get {
                return ResourceManager.GetString("MainForm_ClearToolStripMenuItemClick_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the application?.
        /// </summary>
        internal static string MainForm_MainFormFormClosing_Are_you_sure_you_want_to_close_the_application_ {
            get {
                return ResourceManager.GetString("MainForm_MainFormFormClosing_Are_you_sure_you_want_to_close_the_application_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string MainForm_MainFormFormClosing_Confirmation {
            get {
                return ResourceManager.GetString("MainForm_MainFormFormClosing_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the reading List?.
        /// </summary>
        internal static string MainForm_RestoreToolStripMenuItemClick_Are_you_sure_you_want_to_clear_the_reading_List_ {
            get {
                return ResourceManager.GetString("MainForm_RestoreToolStripMenuItemClick_Are_you_sure_you_want_to_clear_the_reading" +
                        "_List_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection [N/A]: Cannot Fetch RSS feeds..
        /// </summary>
        internal static string MainForm_RssCheckTimerTick_Internet_Connection__N_A___Cannot_Fetch_RSS_feeds_ {
            get {
                return ResourceManager.GetString("MainForm_RssCheckTimerTick_Internet_Connection__N_A___Cannot_Fetch_RSS_feeds_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet Connection Available.
        /// </summary>
        internal static string MainForm_RssStatusChecker_No_Internet_Connection_Available {
            get {
                return ResourceManager.GetString("MainForm_RssStatusChecker_No_Internet_Connection_Available", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap navigation {
            get {
                object obj = ResourceManager.GetObject("navigation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigation_180 {
            get {
                object obj = ResourceManager.GetObject("navigation_180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reload_48 {
            get {
                object obj = ResourceManager.GetObject("reload_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert empty field!.
        /// </summary>
        internal static string SubscriptionManagerForm_AddSubButtonClick_Cannot_insert_empty_field_ {
            get {
                return ResourceManager.GetString("SubscriptionManagerForm_AddSubButtonClick_Cannot_insert_empty_field_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t get Channel Info.
        /// </summary>
        internal static string SubscriptionManagerForm_AddSubButtonClick_Couldn_t_get_Channel_Info {
            get {
                return ResourceManager.GetString("SubscriptionManagerForm_AddSubButtonClick_Couldn_t_get_Channel_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string SubscriptionManagerForm_AddSubButtonClick_Information {
            get {
                return ResourceManager.GetString("SubscriptionManagerForm_AddSubButtonClick_Information", resourceCulture);
            }
        }
    }
}
